### ISSUE TITLE
atom.keymap no longer exists

### ISSUE THREAD

**Issue by johngeorgewright** [atom/api#13]
From the [KeymapManager](https://atom.io/docs/api/v1.0.2/KeymapManager) docs:

> In Atom, you can access a global instance of this object via `atom.keymap`.

This doesn't seem to be true anymore.

**Comment by johngeorgewright** [comment]
Ah.. it's `atom.keymaps`.

**Comment by thomasjo** [comment]
This was fixed in https://github.com/atom/atom-keymap/pull/91. Documentation will be refreshed as part of the next release of Atom.

**Comment by johngeorgewright** [comment]
Ideal.
